#pragma warning disable 0649
//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.ComponentModel;

namespace WriteTests.TypedListClasses
{
	/// <summary>Class which represents a row in the typed list 'OrderCustomer'.</summary>
	/// <remarks>Contains the following entity definition(s):
	/// Entity: Customer. <br/>
	/// Entity: Order. <br/>
	/// Custom Properties: <br/>
	/// </remarks>
	public partial class OrderCustomerTypedListRow 
	{
		#region Class Member Declarations
		private System.Int32	_orderId;
		private System.String	_companyName;
		private System.String	_contactPerson;
		private Nullable<System.Int32>	_employeeId;
		private System.DateTime	_orderDate;
		private System.Int32	_customerId;
		private Nullable<System.DateTime>	_requiredDate;
		private Nullable<System.DateTime>	_shippedDate;
		#endregion

		#region Extensibility Method Definitions
		partial void OnCreated();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="OrderCustomerTypedListRow"/> class.</summary>
		public OrderCustomerTypedListRow()
		{
			OnCreated();
		}

		#region Class Property Declarations
		/// <summary>Gets the OrderId field. Mapped onto 'Order.OrderId'</summary>
		public System.Int32 OrderId
		{
			get	{ return _orderId; }
			internal set { _orderId = value;}
		}
		
		/// <summary>Gets the CompanyName field. Mapped onto 'Customer.CompanyName'</summary>
		public System.String CompanyName
		{
			get	{ return _companyName; }
			internal set { _companyName = value;}
		}
		
		/// <summary>Gets the ContactPerson field. Mapped onto 'Customer.ContactPerson'</summary>
		public System.String ContactPerson
		{
			get	{ return _contactPerson; }
			internal set { _contactPerson = value;}
		}
		
		/// <summary>Gets the EmployeeId field. Mapped onto 'Order.EmployeeId'</summary>
		public Nullable<System.Int32> EmployeeId
		{
			get	{ return _employeeId; }
			internal set { _employeeId = value;}
		}
		
		/// <summary>Gets the OrderDate field. Mapped onto 'Order.OrderDate'</summary>
		public System.DateTime OrderDate
		{
			get	{ return _orderDate; }
			internal set { _orderDate = value;}
		}
		
		/// <summary>Gets the CustomerId field. Mapped onto 'Order.CustomerId'</summary>
		public System.Int32 CustomerId
		{
			get	{ return _customerId; }
			internal set { _customerId = value;}
		}
		
		/// <summary>Gets the RequiredDate field. Mapped onto 'Order.RequiredDate'</summary>
		public Nullable<System.DateTime> RequiredDate
		{
			get	{ return _requiredDate; }
			internal set { _requiredDate = value;}
		}
		
		/// <summary>Gets the ShippedDate field. Mapped onto 'Order.ShippedDate'</summary>
		public Nullable<System.DateTime> ShippedDate
		{
			get	{ return _shippedDate; }
			internal set { _shippedDate = value;}
		}
		
		#endregion
	}
}
#pragma warning restore 0649
