#pragma warning disable 0649
//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.ComponentModel;

namespace WriteTests.TypedListClasses
{
	/// <summary>Class which represents a row in the typed list 'Product_'.</summary>
	/// <remarks>Contains the following entity definition(s):
	/// Entity: Product. <br/>
	/// Custom Properties: <br/>
	/// </remarks>
	public partial class Product_TypedListRow 
	{
		#region Class Member Declarations
		private System.Guid	_productId;
		private System.String	_shortDescription;
		private System.String	_fullDescription;
		private Nullable<System.Decimal>	_price;
		private System.Guid	_testRunId;
		#endregion

		#region Extensibility Method Definitions
		partial void OnCreated();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="Product_TypedListRow"/> class.</summary>
		public Product_TypedListRow()
		{
			OnCreated();
		}

		#region Class Property Declarations
		/// <summary>Gets the ProductId field. Mapped onto 'Product.ProductId'</summary>
		public System.Guid ProductId
		{
			get	{ return _productId; }
			internal set { _productId = value;}
		}
		
		/// <summary>Gets the ShortDescription field. Mapped onto 'Product.ShortDescription'</summary>
		public System.String ShortDescription
		{
			get	{ return _shortDescription; }
			internal set { _shortDescription = value;}
		}
		
		/// <summary>Gets the FullDescription field. Mapped onto 'Product.FullDescription'</summary>
		public System.String FullDescription
		{
			get	{ return _fullDescription; }
			internal set { _fullDescription = value;}
		}
		
		/// <summary>Gets the Price field. Mapped onto 'Product.Price'</summary>
		public Nullable<System.Decimal> Price
		{
			get	{ return _price; }
			internal set { _price = value;}
		}
		
		/// <summary>Gets the TestRunId field. Mapped onto 'Product.TestRunId'</summary>
		public System.Guid TestRunId
		{
			get	{ return _testRunId; }
			internal set { _testRunId = value;}
		}
		
		#endregion
	}
}
#pragma warning restore 0649
