-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v4.2  Build: December 4th, 2014
-- SQL Server 2000/2005/2008/2008R2/2012/Express DDL Script generated from project: WriteTests
-- Project filename: LinqToSQL2\tests\SourceProjects\WriteTests.llblgenproj
-- Script generated on: 09-jan-2015 13:19.49
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 

USE [LLBLGenProUnitTest]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP Foreign keys
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[BallColor] DROP CONSTRAINT [FK_2cdcc0341808d95862abaaba251]
GO

ALTER TABLE [dbo].[BallColor] DROP CONSTRAINT [FK_b72dd0f40319eb7aad2c683b343]
GO

ALTER TABLE [dbo].[CompanyProperty] DROP CONSTRAINT [FK_CompanyProperty_Company]
GO

ALTER TABLE [dbo].[Customer] DROP CONSTRAINT [FK_Customer_Address]
GO

ALTER TABLE [dbo].[Customer] DROP CONSTRAINT [FK_Customer_Address1]
GO

ALTER TABLE [dbo].[Employee] DROP CONSTRAINT [FK_Employee_Employee]
GO

ALTER TABLE [dbo].[Order] DROP CONSTRAINT [FK_Order_Customer]
GO

ALTER TABLE [dbo].[Order] DROP CONSTRAINT [FK_Order_Employee]
GO

ALTER TABLE [dbo].[OrderRow] DROP CONSTRAINT [FK_OrderRow_Order]
GO

ALTER TABLE [dbo].[OrderRow] DROP CONSTRAINT [FK_OrderRow_Product]
GO

ALTER TABLE [dbo].[SpecialCustomer] DROP CONSTRAINT [FK_SpecialCustomer_Customer]
GO

ALTER TABLE [dbo].[SpecialProduct] DROP CONSTRAINT [FK_SpecialProduct_Product]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'dbo' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE [dbo].[Address]
GO

DROP TABLE [dbo].[AuditInfo]
GO

DROP TABLE [dbo].[Ball]
GO

DROP TABLE [dbo].[BallColor]
GO

DROP TABLE [dbo].[Color]
GO

DROP TABLE [dbo].[Company]
GO

DROP TABLE [dbo].[CompanyProperty]
GO

DROP TABLE [dbo].[Customer]
GO

DROP TABLE [dbo].[Employee]
GO

DROP TABLE [dbo].[EnumTester]
GO

DROP TABLE [dbo].[GuidTPEHTester]
GO

DROP TABLE [dbo].[NoPk]
GO

DROP TABLE [dbo].[Order]
GO

DROP TABLE [dbo].[OrderRow]
GO

DROP TABLE [dbo].[Product]
GO

DROP TABLE [dbo].[SpecialCustomer]
GO

DROP TABLE [dbo].[SpecialProduct]
GO

DROP TABLE [dbo].[SplitOffTest]
GO
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'LLBLGenProUnitTest'
-- ----------------------------------------------------------------------------------------------------------------

USE master
GO
CREATE DATABASE [LLBLGenProUnitTest] /* ON PRIMARY (NAME=LLBLGenProUnitTest_dat, FILENAME='c:\mycatalogs\LLBLGenProUnitTest.mdf', SIZE=10MB) */
GO


USE [LLBLGenProUnitTest]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[Address] 
(
	[AddressId] [int] IDENTITY (1,1) NOT NULL, 
	[StreetName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[HouseNumber] [int] NOT NULL, 
	[Zipcode] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[TestRunID] [uniqueidentifier] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[AuditInfo] 
(
	[ID] [int] IDENTITY (1,1) NOT NULL, 
	[ActionType] [int] NOT NULL, 
	[AffectedEntityName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[ActionDateTime] [datetime] NOT NULL, 
	[ActionData] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Ball] 
(
	[Diameter] [int] NOT NULL, 
	[Id] [int] IDENTITY (1,1) NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[BallColor] 
(
	[BallId] [int] NOT NULL, 
	[ColorId] [int] NOT NULL, 
	[Id] [int] IDENTITY (1,1) NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Color] 
(
	[Description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Id] [int] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Company] 
(
	[CompanyID] [binary] NOT NULL, 
	[CompanyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[TestrunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CompanyProperty] 
(
	[PropertyID] [binary] NOT NULL, 
	[CompanyID] [binary] NOT NULL, 
	[PropertyValue] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[TestrunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Customer] 
(
	[CustomerID] [int] IDENTITY (1,1) NOT NULL, 
	[CompanyName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[CustomerSince] [datetime] NOT NULL, 
	[ContactPerson] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[CompanyEmailAddress] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[VisitingAddressID] [int] NOT NULL, 
	[BillingAddressID] [int] NOT NULL, 
	[TestRunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Employee] 
(
	[EmployeeID] [int] IDENTITY (1,1) NOT NULL, 
	[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[EmployeeSince] [datetime] NOT NULL, 
	[ManagedBy] [int] NULL, 
	[Photo] [image] NULL, 
	[TestRunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[EnumTester] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[EnumField] [int] NOT NULL, 
	[NullableEnumField] [int] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[GuidTPEHTester] 
(
	[ID] [uniqueidentifier] NOT NULL, 
	[ItemType] [int] NOT NULL, 
	[Element1] [int] NULL, 
	[Element2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[TestrunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[NoPk] 
(
	[ID] [int] NOT NULL, 
	[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Order] 
(
	[OrderID] [int] IDENTITY (1,1) NOT NULL, 
	[CustomerID] [int] NOT NULL, 
	[EmployeeID] [int] NULL, 
	[OrderDate] [datetime] NOT NULL, 
	[RequiredDate] [datetime] NULL, 
	[ShippedDate] [datetime] NULL, 
	[TestRunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[OrderRow] 
(
	[OrderID] [int] NOT NULL, 
	[ProductID] [uniqueidentifier] NOT NULL, 
	[Quantity] [int] NOT NULL, 
	[PriceInvoiced] [decimal] (11, 2) NOT NULL, 
	[TestRunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Product] 
(
	[ProductID] [uniqueidentifier] NOT NULL, 
	[ShortDescription] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[FullDescription] [text] NULL, 
	[Price] [decimal] (11, 2) NULL, 
	[TestRunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SpecialCustomer] 
(
	[CustomerID] [int] NOT NULL, 
	[Discount] [real] NOT NULL, 
	[TestRunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SpecialProduct] 
(
	[ProductID] [uniqueidentifier] NOT NULL, 
	[ActionCode] [int] NOT NULL, 
	[ActionDate] [datetime] NULL, 
	[TestrunID] [uniqueidentifier] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SplitOffTest] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[FirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[LastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Photo] [image] NULL, 
	[Notes] [ntext] NULL 
) ON [PRIMARY]
GO

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints, Unique constraints and Default Values
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'LLBLGenProUnitTest'
-- ----------------------------------------------------------------------------------------------------------------

USE [LLBLGenProUnitTest]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Address] WITH NOCHECK 
	ADD CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED 
	( 
		[AddressId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AuditInfo] WITH NOCHECK 
	ADD CONSTRAINT [PK_AuditInfo] PRIMARY KEY CLUSTERED 
	( 
		[ID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Ball] WITH NOCHECK 
	ADD CONSTRAINT [PK_5d30b2a4eebb6d8e424e315f1a9] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BallColor] WITH NOCHECK 
	ADD CONSTRAINT [PK_70dc3ab4567926181fcf1fc53a4] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Color] WITH NOCHECK 
	ADD CONSTRAINT [PK_2f7a9f74cda8f58e1a25b03a1f7] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Company] WITH NOCHECK 
	ADD CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED 
	( 
		[CompanyID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CompanyProperty] WITH NOCHECK 
	ADD CONSTRAINT [PK_CompanyProperty] PRIMARY KEY CLUSTERED 
	( 
		[PropertyID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Customer] WITH NOCHECK 
	ADD CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
	( 
		[CustomerID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Employee] WITH NOCHECK 
	ADD CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
	( 
		[EmployeeID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EnumTester] WITH NOCHECK 
	ADD CONSTRAINT [PK_82edc26456dbd8bf66fe04bdba6] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GuidTPEHTester] WITH NOCHECK 
	ADD CONSTRAINT [PK_GuidTPEHTester] PRIMARY KEY CLUSTERED 
	( 
		[ID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Order] WITH NOCHECK 
	ADD CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
	( 
		[OrderID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[OrderRow] WITH NOCHECK 
	ADD CONSTRAINT [PK_OrderRow] PRIMARY KEY CLUSTERED 
	( 
		[OrderID], [ProductID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Product] WITH NOCHECK 
	ADD CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
	( 
		[ProductID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SpecialCustomer] WITH NOCHECK 
	ADD CONSTRAINT [PK_SpecialCustomer] PRIMARY KEY CLUSTERED 
	( 
		[CustomerID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SpecialProduct] WITH NOCHECK 
	ADD CONSTRAINT [PK_SpecialProduct] PRIMARY KEY CLUSTERED 
	( 
		[ProductID] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SplitOffTest] WITH NOCHECK 
	ADD CONSTRAINT [PK_cde8582407aa15fe49a3580ba26] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	) ON [PRIMARY]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Customer] 
	ADD CONSTRAINT [IX_Customer_1] UNIQUE NONCLUSTERED
	(
		[BillingAddressID] 
	)
GO

ALTER TABLE [dbo].[Customer] 
	ADD CONSTRAINT [IX_Customer_2] UNIQUE NONCLUSTERED
	(
		[VisitingAddressID] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
ALTER TABLE [dbo].[Customer] 
	ADD CONSTRAINT [DV_Customer_BillingAddressID] DEFAULT (0) FOR [BillingAddressID]
GO
ALTER TABLE [dbo].[Product] 
	ADD CONSTRAINT [DV_Product_Price] DEFAULT (1.0) FOR [Price]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- All foreign Key constraints
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[BallColor] 
	ADD CONSTRAINT [FK_2cdcc0341808d95862abaaba251] FOREIGN KEY
	(
		[ColorId] 
	)
	REFERENCES [dbo].[Color]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[BallColor] 
	ADD CONSTRAINT [FK_b72dd0f40319eb7aad2c683b343] FOREIGN KEY
	(
		[BallId] 
	)
	REFERENCES [dbo].[Ball]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[CompanyProperty] 
	ADD CONSTRAINT [FK_CompanyProperty_Company] FOREIGN KEY
	(
		[CompanyID] 
	)
	REFERENCES [dbo].[Company]
	(
		[CompanyID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Customer] 
	ADD CONSTRAINT [FK_Customer_Address] FOREIGN KEY
	(
		[VisitingAddressID] 
	)
	REFERENCES [dbo].[Address]
	(
		[AddressId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Customer] 
	ADD CONSTRAINT [FK_Customer_Address1] FOREIGN KEY
	(
		[BillingAddressID] 
	)
	REFERENCES [dbo].[Address]
	(
		[AddressId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Employee] 
	ADD CONSTRAINT [FK_Employee_Employee] FOREIGN KEY
	(
		[ManagedBy] 
	)
	REFERENCES [dbo].[Employee]
	(
		[EmployeeID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Order] 
	ADD CONSTRAINT [FK_Order_Customer] FOREIGN KEY
	(
		[CustomerID] 
	)
	REFERENCES [dbo].[Customer]
	(
		[CustomerID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Order] 
	ADD CONSTRAINT [FK_Order_Employee] FOREIGN KEY
	(
		[EmployeeID] 
	)
	REFERENCES [dbo].[Employee]
	(
		[EmployeeID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[OrderRow] 
	ADD CONSTRAINT [FK_OrderRow_Order] FOREIGN KEY
	(
		[OrderID] 
	)
	REFERENCES [dbo].[Order]
	(
		[OrderID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[OrderRow] 
	ADD CONSTRAINT [FK_OrderRow_Product] FOREIGN KEY
	(
		[ProductID] 
	)
	REFERENCES [dbo].[Product]
	(
		[ProductID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[SpecialCustomer] 
	ADD CONSTRAINT [FK_SpecialCustomer_Customer] FOREIGN KEY
	(
		[CustomerID] 
	)
	REFERENCES [dbo].[Customer]
	(
		[CustomerID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[SpecialProduct] 
	ADD CONSTRAINT [FK_SpecialProduct_Product] FOREIGN KEY
	(
		[ProductID] 
	)
	REFERENCES [dbo].[Product]
	(
		[ProductID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO

-----------------------
-- Stored procs needed for tests. Added to script manually
-----------------------


CREATE   PROCEDURE pr_ClearAll
AS
DELETE FROM SpecialCustomer
DELETE FROM OrderRow
DELETE FROM [Order]
DELETE FROM SpecialProduct
DELETE FROM Product
DELETE FROM Customer
DELETE FROM Address
UPDATE Employee SET ManagedBy=NULL
DELETE FROM Employee
DELETE FROM CompanyProperty 
DELETE FROM Company
DELETE FROM GuidTPEHTester
DELETE FROM SplitOffTest
GO

CREATE   PROCEDURE pr_ClearTestRunData
	@testRunID uniqueidentifier
AS
DELETE FROM SpecialCustomer WHERE TestRunID = @testRunID
DELETE FROM OrderRow WHERE TestRunID = @testRunID
DELETE FROM [Order] WHERE TestRunID = @testRunID
DELETE FROM SpecialProduct WHERE TestRunID = @testRunID
DELETE FROM Product WHERE TestRunID = @testRunID
DELETE FROM Customer WHERE TestRunID = @testRunID
DELETE FROM Address WHERE TestRunID = @testRunID
UPDATE Employee SET ManagedBy=NULL WHERE TestRunID = @testRunID
DELETE FROM Employee WHERE TestRunID = @testRunID
DELETE FROM CompanyProperty WHERE TestRunID=@testRunID
DELETE FROM Company WHERE TestRunID=@testRunID
DELETE FROM GuidTPEHTester WHERE TestRunID = @testrunid
DELETE FROM SplitOffTest
GO