#pragma warning disable 0649
//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.ComponentModel;

namespace ReadTestsAdventureWorks2008.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'BillOfRightsResult'.</summary>
	public partial class BillOfRightsResultTypedViewRow 
	{
		#region Class Member Declarations
		private Nullable<System.Int16>	_bomlevel;
		private System.String	_componentDesc;
		private Nullable<System.Int32>	_componentId;
		private Nullable<System.Decimal>	_listPrice;
		private Nullable<System.Int32>	_productAssemblyId;
		private Nullable<System.Int32>	_recursionLevel;
		private Nullable<System.Decimal>	_standardCost;
		private Nullable<System.Decimal>	_totalQuantity;
		#endregion

		#region Extensibility Method Definitions
		partial void OnCreated();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="BillOfRightsResultTypedViewRow"/> class.</summary>
		public BillOfRightsResultTypedViewRow()
		{
			OnCreated();
		}

		#region Class Property Declarations
		/// <summary>Gets the Bomlevel field. Mapped onto target field / column 'BOMLevel'. </summary>
		public Nullable<System.Int16> Bomlevel
		{
			get	{ return _bomlevel; }
		}
		
		/// <summary>Gets the ComponentDesc field. Mapped onto target field / column 'ComponentDesc'. </summary>
		public System.String ComponentDesc
		{
			get	{ return _componentDesc; }
		}
		
		/// <summary>Gets the ComponentId field. Mapped onto target field / column 'ComponentID'. </summary>
		public Nullable<System.Int32> ComponentId
		{
			get	{ return _componentId; }
		}
		
		/// <summary>Gets the ListPrice field. Mapped onto target field / column 'ListPrice'. </summary>
		public Nullable<System.Decimal> ListPrice
		{
			get	{ return _listPrice; }
		}
		
		/// <summary>Gets the ProductAssemblyId field. Mapped onto target field / column 'ProductAssemblyID'. </summary>
		public Nullable<System.Int32> ProductAssemblyId
		{
			get	{ return _productAssemblyId; }
		}
		
		/// <summary>Gets the RecursionLevel field. Mapped onto target field / column 'RecursionLevel'. </summary>
		public Nullable<System.Int32> RecursionLevel
		{
			get	{ return _recursionLevel; }
		}
		
		/// <summary>Gets the StandardCost field. Mapped onto target field / column 'StandardCost'. </summary>
		public Nullable<System.Decimal> StandardCost
		{
			get	{ return _standardCost; }
		}
		
		/// <summary>Gets the TotalQuantity field. Mapped onto target field / column 'TotalQuantity'. </summary>
		public Nullable<System.Decimal> TotalQuantity
		{
			get	{ return _totalQuantity; }
		}
		
		#endregion
	}
}
#pragma warning restore 0649
