#pragma warning disable 0649
//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.ComponentModel;

namespace ReadTestsAdventureWorks2008.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'UfnGetContactInformationResult'.</summary>
	public partial class UfnGetContactInformationResultTypedViewRow 
	{
		#region Class Member Declarations
		private System.String	_businessEntityType;
		private System.String	_firstName;
		private System.String	_jobTitle;
		private System.String	_lastName;
		private System.Int32	_personId;
		#endregion

		#region Extensibility Method Definitions
		partial void OnCreated();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="UfnGetContactInformationResultTypedViewRow"/> class.</summary>
		public UfnGetContactInformationResultTypedViewRow()
		{
			OnCreated();
		}

		#region Class Property Declarations
		/// <summary>Gets the BusinessEntityType field. Mapped onto target field / column 'BusinessEntityType'. </summary>
		public System.String BusinessEntityType
		{
			get	{ return _businessEntityType; }
		}
		
		/// <summary>Gets the FirstName field. Mapped onto target field / column 'FirstName'. </summary>
		public System.String FirstName
		{
			get	{ return _firstName; }
		}
		
		/// <summary>Gets the JobTitle field. Mapped onto target field / column 'JobTitle'. </summary>
		public System.String JobTitle
		{
			get	{ return _jobTitle; }
		}
		
		/// <summary>Gets the LastName field. Mapped onto target field / column 'LastName'. </summary>
		public System.String LastName
		{
			get	{ return _lastName; }
		}
		
		/// <summary>Gets the PersonId field. Mapped onto target field / column 'PersonID'. </summary>
		public System.Int32 PersonId
		{
			get	{ return _personId; }
		}
		
		#endregion
	}
}
#pragma warning restore 0649
