#pragma warning disable 0649
//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.ComponentModel;

namespace WriteTests.EntityClasses
{
	/// <summary>Class which represents the entity 'DerivedType1', mapped on table 'LLBLGenProUnitTest.dbo.GuidTPEHTester'.</summary>
	public partial class DerivedType1 : GuidTpehTester
	{
		#region Class Member Declarations
		private System.String	_element2;
		#endregion
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnElement2Changing(System.String value);
		partial void OnElement2Changed();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="DerivedType1"/> class.</summary>
		public DerivedType1()
		{
			
			OnCreated();
		}


		#region Class Property Declarations
		/// <summary>Gets or sets the Element2 field. Mapped on target field 'Element2'. </summary>
		public System.String Element2
		{
			get	{ return _element2; }
			set
			{
				if((_element2 != value))
				{
					OnElement2Changing(value);
					SendPropertyChanging("Element2");
					_element2 = value;
					SendPropertyChanged("Element2");
					OnElement2Changed();
				}
			}
		}

		#endregion
	}
}
#pragma warning restore 0649