#pragma warning disable 0649
//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.ComponentModel;

namespace WriteTests.EntityClasses
{
	/// <summary>Class which represents the entity 'EnumTester', mapped on table 'LLBLGenProUnitTest.dbo.EnumTester'.</summary>
	public partial class EnumTester : INotifyPropertyChanging, INotifyPropertyChanged
	{
		#region Events
		/// <summary>Event which is raised when a property value is changing.</summary>
		public event PropertyChangingEventHandler PropertyChanging;
		/// <summary>Event which is raised when a property value changes.</summary>
		public event PropertyChangedEventHandler PropertyChanged;
		#endregion
		
		#region Class Member Declarations
		private System.ConsoleColor	_enumField;
		private System.Int32	_id;
		private Nullable<System.ConsoleColor>	_nullableEnumField;
		#endregion
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnEnumFieldChanging(System.ConsoleColor value);
		partial void OnEnumFieldChanged();
		partial void OnIdChanging(System.Int32 value);
		partial void OnIdChanged();
		partial void OnNullableEnumFieldChanging(Nullable<System.ConsoleColor> value);
		partial void OnNullableEnumFieldChanged();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="EnumTester"/> class.</summary>
		public EnumTester()
		{
			OnCreated();
		}

		/// <summary>Raises the PropertyChanging event</summary>
		/// <param name="propertyName">name of the property which is changing</param>
		protected virtual void SendPropertyChanging(string propertyName)
		{
			if((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>Raises the PropertyChanged event for the property specified</summary>
		/// <param name="propertyName">name of the property which was changed</param>
		protected virtual void SendPropertyChanged(string propertyName)
		{
			if((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		

		#region Class Property Declarations
		/// <summary>Gets or sets the EnumField field. Mapped on target field 'EnumField'. </summary>
		public System.ConsoleColor EnumField
		{
			get	{ return _enumField; }
			set
			{
				if((_enumField != value))
				{
					OnEnumFieldChanging(value);
					SendPropertyChanging("EnumField");
					_enumField = value;
					SendPropertyChanged("EnumField");
					OnEnumFieldChanged();
				}
			}
		}

		/// <summary>Gets or sets the Id field. Mapped on target field 'Id'. </summary>
		public System.Int32 Id
		{
			get	{ return _id; }
			set
			{
				if((_id != value))
				{
					OnIdChanging(value);
					SendPropertyChanging("Id");
					_id = value;
					SendPropertyChanged("Id");
					OnIdChanged();
				}
			}
		}

		/// <summary>Gets or sets the NullableEnumField field. Mapped on target field 'NullableEnumField'. </summary>
		public Nullable<System.ConsoleColor> NullableEnumField
		{
			get	{ return _nullableEnumField; }
			set
			{
				if((_nullableEnumField != value))
				{
					OnNullableEnumFieldChanging(value);
					SendPropertyChanging("NullableEnumField");
					_nullableEnumField = value;
					SendPropertyChanged("NullableEnumField");
					OnNullableEnumFieldChanged();
				}
			}
		}

		#endregion
	}
}
#pragma warning restore 0649