//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.Linq.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.Linq.Properties.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has no identity key.
        /// </summary>
        internal static string ArgumentTypeHasNoIdentityKey {
            get {
                return ResourceManager.GetString("ArgumentTypeHasNoIdentityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add change conflicts. They are added automatically during SubmitChanges..
        /// </summary>
        internal static string CannotAddChangeConflicts {
            get {
                return ResourceManager.GetString("CannotAddChangeConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt has been made to Attach or Add an entity that is not new, perhaps having been loaded from another DataContext.  This is not supported..
        /// </summary>
        internal static string CannotAttachAddNonNewEntities {
            get {
                return ResourceManager.GetString("CannotAttachAddNonNewEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot attach an entity that already exists..
        /// </summary>
        internal static string CannotAttachAlreadyExistingEntity {
            get {
                return ResourceManager.GetString("CannotAttachAlreadyExistingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity can only be attached as modified without original state if it declares a version member or does not have an update check policy..
        /// </summary>
        internal static string CannotAttachAsModifiedWithoutOriginalState {
            get {
                return ResourceManager.GetString("CannotAttachAsModifiedWithoutOriginalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed: Inheritance discriminator change from &apos;{0}&apos; to &apos;{1}&apos; would change type from &apos;{2}&apos; to &apos;{3}&apos;..
        /// </summary>
        internal static string CannotChangeInheritanceType {
            get {
                return ResourceManager.GetString("CannotChangeInheritanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t perform Create, Update or Delete operations on &apos;{0}&apos; because it has no primary key..
        /// </summary>
        internal static string CannotPerformCUDOnReadOnlyTable {
            get {
                return ResourceManager.GetString("CannotPerformCUDOnReadOnlyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation cannot be performed during a call to SubmitChanges..
        /// </summary>
        internal static string CannotPerformOperationDuringSubmitChanges {
            get {
                return ResourceManager.GetString("CannotPerformOperationDuringSubmitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation cannot be performed for the entity because it is not being change tracked..
        /// </summary>
        internal static string CannotPerformOperationForUntrackedObject {
            get {
                return ResourceManager.GetString("CannotPerformOperationForUntrackedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation can only be performed inside a user override method during a call to SubmitChanges..
        /// </summary>
        internal static string CannotPerformOperationOutsideSubmitChanges {
            get {
                return ResourceManager.GetString("CannotPerformOperationOutsideSubmitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove change conflicts. .
        /// </summary>
        internal static string CannotRemoveChangeConflicts {
            get {
                return ResourceManager.GetString("CannotRemoveChangeConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove an entity that has not been attached..
        /// </summary>
        internal static string CannotRemoveUnattachedEntity {
            get {
                return ResourceManager.GetString("CannotRemoveUnattachedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an entity that already exists..
        /// </summary>
        internal static string CantAddAlreadyExistingItem {
            get {
                return ResourceManager.GetString("CantAddAlreadyExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an entity with a key that is already in use..
        /// </summary>
        internal static string CantAddAlreadyExistingKey {
            get {
                return ResourceManager.GetString("CantAddAlreadyExistingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: The database column &apos;{0}&apos; is mapped more than once..
        /// </summary>
        internal static string ColumnMappedMoreThanOnce {
            get {
                return ResourceManager.GetString("ColumnMappedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists in data context..
        /// </summary>
        internal static string CouldNotAttach {
            get {
                return ResourceManager.GetString("CouldNotAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert from type &apos;{0}&apos; to type &apos;{1}&apos;..
        /// </summary>
        internal static string CouldNotConvert {
            get {
                return ResourceManager.GetString("CouldNotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve a Table for inheritance subtype &apos;{0}&apos;, try Table of {1} instead..
        /// </summary>
        internal static string CouldNotGetTableForSubtype {
            get {
                return ResourceManager.GetString("CouldNotGetTableForSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to remove a relationship between a {0} and a {1}. However, one of the relationship&apos;s foreign keys ({2}) cannot be set to null..
        /// </summary>
        internal static string CouldNotRemoveRelationshipBecauseOneSideCannotBeNull {
            get {
                return ResourceManager.GetString("CouldNotRemoveRelationshipBecauseOneSideCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cycle was detected in the set of changes.
        /// </summary>
        internal static string CycleDetected {
            get {
                return ResourceManager.GetString("CycleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database generated a key that is already in use..
        /// </summary>
        internal static string DatabaseGeneratedAlreadyExistingKey {
            get {
                return ResourceManager.GetString("DatabaseGeneratedAlreadyExistingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataContext accessed after Dispose..
        /// </summary>
        internal static string DataContextCannotBeUsedAfterDispose {
            get {
                return ResourceManager.GetString("DataContextCannotBeUsedAfterDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of member &apos;{0}&apos; of an object of type &apos;{1}&apos; changed. A member that is computed or generated by the database cannot be changed..
        /// </summary>
        internal static string DbGeneratedChangeNotAllowed {
            get {
                return ResourceManager.GetString("DbGeneratedChangeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferred loading requires that object tracking is also enabled..
        /// </summary>
        internal static string DeferredLoadingRequiresObjectTracking {
            get {
                return ResourceManager.GetString("DeferredLoadingRequiresObjectTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Callback into user code for delete..
        /// </summary>
        internal static string DeleteCallbackComment {
            get {
                return ResourceManager.GetString("DeleteCallbackComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity is not of the correct type..
        /// </summary>
        internal static string EntityIsTheWrongType {
            get {
                return ResourceManager.GetString("EntityIsTheWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntitySet is already loaded and the source cannot be changed..
        /// </summary>
        internal static string EntitySetAlreadyLoaded {
            get {
                return ResourceManager.GetString("EntitySetAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an instance of an abstract class to EntitySet&lt;{0}&gt;..
        /// </summary>
        internal static string EntitySetDataBindingWithAbstractBaseClass {
            get {
                return ResourceManager.GetString("EntitySetDataBindingWithAbstractBaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have a parameterless constructor when using IBindingList to add new instances..
        /// </summary>
        internal static string EntitySetDataBindingWithNonPublicDefaultConstructor {
            get {
                return ResourceManager.GetString("EntitySetDataBindingWithNonPublicDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitySet was modified during enumeration..
        /// </summary>
        internal static string EntitySetModifiedDuringEnumeration {
            get {
                return ResourceManager.GetString("EntitySetModifiedDuringEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} does not implement {1}..
        /// </summary>
        internal static string ExpectedQueryableArgument {
            get {
                return ResourceManager.GetString("ExpectedQueryableArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected update, delete or change..
        /// </summary>
        internal static string ExpectedUpdateDeleteOrChange {
            get {
                return ResourceManager.GetString("ExpectedUpdateDeleteOrChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of member &apos;{0}&apos; of an object of type &apos;{1}&apos; changed. A member defining the identity of the object cannot be changed. Consider adding a new object with new identity and deleting the existing one instead..
        /// </summary>
        internal static string IdentityChangeNotAllowed {
            get {
                return ResourceManager.GetString("IdentityChangeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles not allowed in LoadOptions LoadWith type graph..
        /// </summary>
        internal static string IncludeCycleNotAllowed {
            get {
                return ResourceManager.GetString("IncludeCycleNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadWith is not allowed after freeze or attach to DataContext..
        /// </summary>
        internal static string IncludeNotAllowedAfterFreeze {
            get {
                return ResourceManager.GetString("IncludeNotAllowedAfterFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; was changed to be inconsistent with the association member &apos;{1}&apos;..
        /// </summary>
        internal static string InconsistentAssociationAndKeyChange {
            get {
                return ResourceManager.GetString("InconsistentAssociationAndKeyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member AutoSync failure. For members to be Auto-Synced after insert, the type must either have an auto-generated identity, or a key that is not modified by the database after insert..
        /// </summary>
        internal static string InsertAutoSyncFailure {
            get {
                return ResourceManager.GetString("InsertAutoSyncFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Callback into user code for insert..
        /// </summary>
        internal static string InsertCallbackComment {
            get {
                return ResourceManager.GetString("InsertCallbackComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression specified must be of the form p.A, where p is the parameter and A is a property or field member. .
        /// </summary>
        internal static string InvalidLoadOptionsLoadMemberSpecification {
            get {
                return ResourceManager.GetString("InvalidLoadOptionsLoadMemberSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is the wrong size. Expected {0}. Actual {1}..
        /// </summary>
        internal static string KeyIsWrongSize {
            get {
                return ResourceManager.GetString("KeyIsWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key value is the wrong type. Expected assignable from {0}. Actual {1}..
        /// </summary>
        internal static string KeyValueIsWrongType {
            get {
                return ResourceManager.GetString("KeyValueIsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting load options is not allowed after results have been returned from a query..
        /// </summary>
        internal static string LoadOptionsChangeNotAllowedAfterQuery {
            get {
                return ResourceManager.GetString("LoadOptionsChangeNotAllowedAfterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not modify EntitySet..
        /// </summary>
        internal static string ModifyDuringAddOrRemove {
            get {
                return ResourceManager.GetString("ModifyDuringAddOrRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid association mapping for member &apos;{0}.{1}&apos;.  &apos;{2}&apos; is not an entity..
        /// </summary>
        internal static string NonEntityAssociationMapping {
            get {
                return ResourceManager.GetString("NonEntityAssociationMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object tracking is not enabled for the current data context instance..
        /// </summary>
        internal static string ObjectTrackingRequired {
            get {
                return ResourceManager.GetString("ObjectTrackingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data context options cannot be modified after results have been returned from a query..
        /// </summary>
        internal static string OptionsCannotBeModifiedAfterQuery {
            get {
                return ResourceManager.GetString("OptionsCannotBeModifiedAfterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The original state instance has the wrong type..
        /// </summary>
        internal static string OriginalEntityIsWrongType {
            get {
                return ResourceManager.GetString("OriginalEntityIsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLinq.
        /// </summary>
        internal static string OwningTeam {
            get {
                return ResourceManager.GetString("OwningTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified provider type &apos;{0}&apos; does not implement &apos;{1}&apos;..
        /// </summary>
        internal static string ProviderDoesNotImplementRequiredInterface {
            get {
                return ResourceManager.GetString("ProviderDoesNotImplementRequiredInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-null provider type expected..
        /// </summary>
        internal static string ProviderTypeNull {
            get {
                return ResourceManager.GetString("ProviderTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to refresh the specified object.  The object no longer exists in the database..
        /// </summary>
        internal static string RefreshOfDeletedObject {
            get {
                return ResourceManager.GetString("RefreshOfDeletedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row not found or changed..
        /// </summary>
        internal static string RowNotFoundOrChanged {
            get {
                return ResourceManager.GetString("RowNotFoundOrChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator &apos;{0}&apos; is not supported in Subquery..
        /// </summary>
        internal static string SubqueryDoesNotSupportOperator {
            get {
                return ResourceManager.GetString("SubqueryDoesNotSupportOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subquery must be a sequence expression..
        /// </summary>
        internal static string SubqueryMustBeSequence {
            get {
                return ResourceManager.GetString("SubqueryMustBeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSubquery is not allowed after freeze or attach to DataContext..
        /// </summary>
        internal static string SubqueryNotAllowedAfterFreeze {
            get {
                return ResourceManager.GetString("SubqueryNotAllowedAfterFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subquery is not supported on &apos;{0}&apos;..
        /// </summary>
        internal static string SubqueryNotSupportedOn {
            get {
                return ResourceManager.GetString("SubqueryNotSupportedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subquery is not supported on &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string SubqueryNotSupportedOnType {
            get {
                return ResourceManager.GetString("SubqueryNotSupportedOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type &apos;{0}&apos; could not be added. This type is not part of the mapped type system..
        /// </summary>
        internal static string TypeCouldNotBeAdded {
            get {
                return ResourceManager.GetString("TypeCouldNotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type &apos;{0}&apos; could not be removed. This type is not part of the mapped type system..
        /// </summary>
        internal static string TypeCouldNotBeRemoved {
            get {
                return ResourceManager.GetString("TypeCouldNotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type &apos;{0}&apos; could not be tracked. This type is not part of the mapped type system..
        /// </summary>
        internal static string TypeCouldNotBeTracked {
            get {
                return ResourceManager.GetString("TypeCouldNotBeTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not an entity..
        /// </summary>
        internal static string TypeIsNotEntity {
            get {
                return ResourceManager.GetString("TypeIsNotEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not mapped as a Table..
        /// </summary>
        internal static string TypeIsNotMarkedAsTable {
            get {
                return ResourceManager.GetString("TypeIsNotMarkedAsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine DataContext for compiled query execution..
        /// </summary>
        internal static string UnableToDetermineDataContext {
            get {
                return ResourceManager.GetString("UnableToDetermineDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Binding Type: {0}.
        /// </summary>
        internal static string UnhandledBindingType {
            get {
                return ResourceManager.GetString("UnhandledBindingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Expression Type: {0}.
        /// </summary>
        internal static string UnhandledExpressionType {
            get {
                return ResourceManager.GetString("UnhandledExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object specified for refresh is not recognized..
        /// </summary>
        internal static string UnrecognizedRefreshObject {
            get {
                return ResourceManager.GetString("UnrecognizedRefreshObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Callback into user code for update..
        /// </summary>
        internal static string UpdateCallbackComment {
            get {
                return ResourceManager.GetString("UpdateCallbackComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} updates failed..
        /// </summary>
        internal static string UpdatesFailedMessage {
            get {
                return ResourceManager.GetString("UpdatesFailedMessage", resourceCulture);
            }
        }
    }
}
