//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.Linq.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mapping() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.Linq.Properties.Mapping", typeof(Mapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract class &apos;{0}&apos; should not be assigned an inheritance discriminator key..
        /// </summary>
        internal static string AbstractClassAssignInheritanceDiscriminator {
            get {
                return ResourceManager.GetString("AbstractClassAssignInheritanceDiscriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Bad function type in mapping for method &apos;{0}&apos;..
        /// </summary>
        internal static string BadFunctionTypeInMethodMapping {
            get {
                return ResourceManager.GetString("BadFunctionTypeInMethodMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find key member &apos;{0}&apos; of key &apos;{1}&apos; on type &apos;{2}&apos;. The key may be wrong or the field or property on &apos;{2}&apos; has changed names..
        /// </summary>
        internal static string BadKeyMember {
            get {
                return ResourceManager.GetString("BadKeyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Storage property: &apos;{0}&apos; on member &apos;{1}.{2}&apos;..
        /// </summary>
        internal static string BadStorageProperty {
            get {
                return ResourceManager.GetString("BadStorageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Cannot get inheritance default from class not mapped into an inheritance hierarchy..
        /// </summary>
        internal static string CannotGetInheritanceDefaultFromNonInheritanceClass {
            get {
                return ResourceManager.GetString("CannotGetInheritanceDefaultFromNonInheritanceClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create PropertyAccessor&lt;{0},{1}&gt; to {2}..
        /// </summary>
        internal static string CouldNotCreateAccessorToProperty {
            get {
                return ResourceManager.GetString("CouldNotCreateAccessorToProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Could not find element type in model for &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotFindElementTypeInModel {
            get {
                return ResourceManager.GetString("CouldNotFindElementTypeInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Could not find required attribute &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string CouldNotFindRequiredAttribute {
            get {
                return ResourceManager.GetString("CouldNotFindRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Cannot find runtime type for type mapping &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotFindRuntimeTypeForMapping {
            get {
                return ResourceManager.GetString("CouldNotFindRuntimeTypeForMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Cannot find type &apos;{0}&apos; from mapping..
        /// </summary>
        internal static string CouldNotFindTypeFromMapping {
            get {
                return ResourceManager.GetString("CouldNotFindTypeFromMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database node not found.  Is the mapping namespace ({0}) correctly specified?.
        /// </summary>
        internal static string DatabaseNodeNotFound {
            get {
                return ResourceManager.GetString("DatabaseNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discriminator &apos;{0}.{1}&apos; may not be type &apos;{2}&apos;..
        /// </summary>
        internal static string DiscriminatorClrTypeNotSupported {
            get {
                return ResourceManager.GetString("DiscriminatorClrTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityRef is already loaded and the source cannot be changed..
        /// </summary>
        internal static string EntityRefAlreadyLoaded {
            get {
                return ResourceManager.GetString("EntityRefAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; must be empty, but contains a node of type {1} named &apos;{2}&apos;..
        /// </summary>
        internal static string ExpectedEmptyElement {
            get {
                return ResourceManager.GetString("ExpectedEmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type mapping for Identity member &apos;{0}.{1}&apos;.  Type &apos;{2}&apos; is not supported for identity members..
        /// </summary>
        internal static string IdentityClrTypeNotSupported {
            get {
                return ResourceManager.GetString("IdentityClrTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect AutoSync specification for member &apos;{0}&apos;..
        /// </summary>
        internal static string IncorrectAutoSyncSpecification {
            get {
                return ResourceManager.GetString("IncorrectAutoSyncSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Incorrect number of parameters mapped for method &apos;{0}&apos;..
        /// </summary>
        internal static string IncorrectNumberOfParametersMappedForMethod {
            get {
                return ResourceManager.GetString("IncorrectNumberOfParametersMappedForMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance code value may not be null..
        /// </summary>
        internal static string InheritanceCodeMayNotBeNull {
            get {
                return ResourceManager.GetString("InheritanceCodeMayNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inheritance code &apos;{0}&apos; is used for multiple types..
        /// </summary>
        internal static string InheritanceCodeUsedForMultipleTypes {
            get {
                return ResourceManager.GetString("InheritanceCodeUsedForMultipleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inheritance hierarchy rooted at &apos;{0}&apos; does not define a default..
        /// </summary>
        internal static string InheritanceHierarchyDoesNotDefineDefault {
            get {
                return ResourceManager.GetString("InheritanceHierarchyDoesNotDefineDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inheritance subtype &apos;{0}&apos; is also declared as a root type..
        /// </summary>
        internal static string InheritanceSubTypeIsAlsoRoot {
            get {
                return ResourceManager.GetString("InheritanceSubTypeIsAlsoRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance type &apos;{0}&apos; does not derive from inheritance root type &apos;{1}&apos;..
        /// </summary>
        internal static string InheritanceTypeDoesNotDeriveFromRoot {
            get {
                return ResourceManager.GetString("InheritanceTypeDoesNotDeriveFromRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inheritance type &apos;{0}&apos; has multiple defaults..
        /// </summary>
        internal static string InheritanceTypeHasMultipleDefaults {
            get {
                return ResourceManager.GetString("InheritanceTypeHasMultipleDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inherited type &apos;{0}&apos; cannot have multiple discriminator key values..
        /// </summary>
        internal static string InheritanceTypeHasMultipleDiscriminators {
            get {
                return ResourceManager.GetString("InheritanceTypeHasMultipleDiscriminators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DeleteOnNull specification for member &apos;{0}&apos;. DeleteOnNull can only be true for singleton association members mapped to non-nullable foreign key columns..
        /// </summary>
        internal static string InvalidDeleteOnNullSpecification {
            get {
                return ResourceManager.GetString("InvalidDeleteOnNullSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create FieldAccessor&lt;{0},{1}&gt; from FieldInfo &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidFieldInfo {
            get {
                return ResourceManager.GetString("InvalidFieldInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid use of generic method &apos;{0}&apos; as mapped function..
        /// </summary>
        internal static string InvalidUseOfGenericMethodAsMappedFunction {
            get {
                return ResourceManager.GetString("InvalidUseOfGenericMethodAsMappedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Link is already loaded and the source cannot be changed..
        /// </summary>
        internal static string LinkAlreadyLoaded {
            get {
                return ResourceManager.GetString("LinkAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column or association &apos;{0}&apos; in the mapping had no corresponding member in type &apos;{1}&apos;. Mapping members from above root type is not supported..
        /// </summary>
        internal static string MappedMemberHadNoCorrespondingMemberInType {
            get {
                return ResourceManager.GetString("MappedMemberHadNoCorrespondingMemberInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Mapping for table &apos;{0}&apos; is not defined..
        /// </summary>
        internal static string MappingForTableUndefined {
            get {
                return ResourceManager.GetString("MappingForTableUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapping of interface member {0}.{1} is not supported..
        /// </summary>
        internal static string MappingOfInterfacesMemberIsNotSupported {
            get {
                return ResourceManager.GetString("MappingOfInterfacesMemberIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; is mapped more than once..
        /// </summary>
        internal static string MemberMappedMoreThanOnce {
            get {
                return ResourceManager.GetString("MemberMappedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; cannot be found..
        /// </summary>
        internal static string MethodCannotBeFound {
            get {
                return ResourceManager.GetString("MethodCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of ThisKey columns is different from the number of OtherKey columns for the association property &apos;{0}&apos; in the type &apos;{1}&apos;..
        /// </summary>
        internal static string MismatchedThisKeyOtherKey {
            get {
                return ResourceManager.GetString("MismatchedThisKeyOtherKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inheritance type &apos;{0}&apos; does not declare a discriminator column..
        /// </summary>
        internal static string NoDiscriminatorFound {
            get {
                return ResourceManager.GetString("NoDiscriminatorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inheritance type &apos;{0}&apos; has a discriminator but is not part of a mapped inheritance hierarchy..
        /// </summary>
        internal static string NonInheritanceClassHasDiscriminator {
            get {
                return ResourceManager.GetString("NonInheritanceClassHasDiscriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result types declared for function &apos;{0}&apos; that returns IMultipleResults..
        /// </summary>
        internal static string NoResultTypesDeclaredForFunction {
            get {
                return ResourceManager.GetString("NoResultTypesDeclaredForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLinq.
        /// </summary>
        internal static string OwningTeam {
            get {
                return ResourceManager.GetString("OwningTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subtype &apos;{0}&apos; cannot contain the primary key member &apos;{1}&apos;..
        /// </summary>
        internal static string PrimaryKeyInSubTypeNotSupported {
            get {
                return ResourceManager.GetString("PrimaryKeyInSubTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified provider type &apos;{0}&apos; not found..
        /// </summary>
        internal static string ProviderTypeNotFound {
            get {
                return ResourceManager.GetString("ProviderTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one result type declared for function &apos;{0}&apos; that does not return IMultipleResults..
        /// </summary>
        internal static string TooManyResultTypesDeclaredForFunction {
            get {
                return ResourceManager.GetString("TooManyResultTypesDeclaredForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members &apos;{0}&apos; and &apos;{1}&apos; both marked as inheritance discriminator..
        /// </summary>
        internal static string TwoMembersMarkedAsInheritanceDiscriminator {
            get {
                return ResourceManager.GetString("TwoMembersMarkedAsInheritanceDiscriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members &apos;{0}&apos; and &apos;{1}&apos; both marked as IsPrimaryKey and IsDbGenerated..
        /// </summary>
        internal static string TwoMembersMarkedAsPrimaryKeyAndDBGenerated {
            get {
                return ResourceManager.GetString("TwoMembersMarkedAsPrimaryKeyAndDBGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members &apos;{0}&apos; and &apos;{1}&apos; both marked as row version..
        /// </summary>
        internal static string TwoMembersMarkedAsRowVersion {
            get {
                return ResourceManager.GetString("TwoMembersMarkedAsRowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assign value to read only property &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToAssignValueToReadonlyProperty {
            get {
                return ResourceManager.GetString("UnableToAssignValueToReadonlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Problem: Unable to resolve root for type &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToResolveRootForType {
            get {
                return ResourceManager.GetString("UnableToResolveRootForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected element &apos;{0}&apos;, but found &apos;{1}&apos;..
        /// </summary>
        internal static string UnexpectedElement {
            get {
                return ResourceManager.GetString("UnexpectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected null &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedNull {
            get {
                return ResourceManager.GetString("UnexpectedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled deferred storage type: {0}..
        /// </summary>
        internal static string UnhandledDeferredStorageType {
            get {
                return ResourceManager.GetString("UnhandledDeferredStorageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class member {0}.{1} is unmapped..
        /// </summary>
        internal static string UnmappedClassMember {
            get {
                return ResourceManager.GetString("UnmappedClassMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized attribute &apos;{0}&apos; in mapping file..
        /// </summary>
        internal static string UnrecognizedAttribute {
            get {
                return ResourceManager.GetString("UnrecognizedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized element &apos;{0}&apos; in mapping file..
        /// </summary>
        internal static string UnrecognizedElement {
            get {
                return ResourceManager.GetString("UnrecognizedElement", resourceCulture);
            }
        }
    }
}
