#pragma warning disable 0649
//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.ComponentModel;

namespace ReadTestsAdventureWorks2008.EntityClasses
{
	/// <summary>Class which represents the entity 'DatabaseLog', mapped on table 'AdventureWorks.dbo.DatabaseLog'.</summary>
	public partial class DatabaseLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		#region Events
		/// <summary>Event which is raised when a property value is changing.</summary>
		public event PropertyChangingEventHandler PropertyChanging;
		/// <summary>Event which is raised when a property value changes.</summary>
		public event PropertyChangedEventHandler PropertyChanged;
		#endregion
		
		#region Class Member Declarations
		private System.Int32	_databaseLogId;
		private System.String	_databaseUser;
		private System.String	_event;
		private System.String	_object;
		private System.DateTime	_postTime;
		private System.String	_schema;
		private System.String	_tsql;
		private System.String	_xmlEvent;
		#endregion
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnDatabaseLogIdChanging(System.Int32 value);
		partial void OnDatabaseLogIdChanged();
		partial void OnDatabaseUserChanging(System.String value);
		partial void OnDatabaseUserChanged();
		partial void OnEventChanging(System.String value);
		partial void OnEventChanged();
		partial void OnObjectChanging(System.String value);
		partial void OnObjectChanged();
		partial void OnPostTimeChanging(System.DateTime value);
		partial void OnPostTimeChanged();
		partial void OnSchemaChanging(System.String value);
		partial void OnSchemaChanged();
		partial void OnTsqlChanging(System.String value);
		partial void OnTsqlChanged();
		partial void OnXmlEventChanging(System.String value);
		partial void OnXmlEventChanged();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="DatabaseLog"/> class.</summary>
		public DatabaseLog()
		{
			OnCreated();
		}

		/// <summary>Raises the PropertyChanging event</summary>
		/// <param name="propertyName">name of the property which is changing</param>
		protected virtual void SendPropertyChanging(string propertyName)
		{
			if((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>Raises the PropertyChanged event for the property specified</summary>
		/// <param name="propertyName">name of the property which was changed</param>
		protected virtual void SendPropertyChanged(string propertyName)
		{
			if((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		

		#region Class Property Declarations
		/// <summary>Gets or sets the DatabaseLogId field. Mapped on target field 'DatabaseLogID'. </summary>
		public System.Int32 DatabaseLogId
		{
			get	{ return _databaseLogId; }
			set
			{
				if((_databaseLogId != value))
				{
					OnDatabaseLogIdChanging(value);
					SendPropertyChanging("DatabaseLogId");
					_databaseLogId = value;
					SendPropertyChanged("DatabaseLogId");
					OnDatabaseLogIdChanged();
				}
			}
		}

		/// <summary>Gets or sets the DatabaseUser field. Mapped on target field 'DatabaseUser'. </summary>
		public System.String DatabaseUser
		{
			get	{ return _databaseUser; }
			set
			{
				if((_databaseUser != value))
				{
					OnDatabaseUserChanging(value);
					SendPropertyChanging("DatabaseUser");
					_databaseUser = value;
					SendPropertyChanged("DatabaseUser");
					OnDatabaseUserChanged();
				}
			}
		}

		/// <summary>Gets or sets the Event field. Mapped on target field 'Event'. </summary>
		public System.String Event
		{
			get	{ return _event; }
			set
			{
				if((_event != value))
				{
					OnEventChanging(value);
					SendPropertyChanging("Event");
					_event = value;
					SendPropertyChanged("Event");
					OnEventChanged();
				}
			}
		}

		/// <summary>Gets or sets the Object field. Mapped on target field 'Object'. </summary>
		public System.String Object
		{
			get	{ return _object; }
			set
			{
				if((_object != value))
				{
					OnObjectChanging(value);
					SendPropertyChanging("Object");
					_object = value;
					SendPropertyChanged("Object");
					OnObjectChanged();
				}
			}
		}

		/// <summary>Gets or sets the PostTime field. Mapped on target field 'PostTime'. </summary>
		public System.DateTime PostTime
		{
			get	{ return _postTime; }
			set
			{
				if((_postTime != value))
				{
					OnPostTimeChanging(value);
					SendPropertyChanging("PostTime");
					_postTime = value;
					SendPropertyChanged("PostTime");
					OnPostTimeChanged();
				}
			}
		}

		/// <summary>Gets or sets the Schema field. Mapped on target field 'Schema'. </summary>
		public System.String Schema
		{
			get	{ return _schema; }
			set
			{
				if((_schema != value))
				{
					OnSchemaChanging(value);
					SendPropertyChanging("Schema");
					_schema = value;
					SendPropertyChanged("Schema");
					OnSchemaChanged();
				}
			}
		}

		/// <summary>Gets or sets the Tsql field. Mapped on target field 'TSQL'. </summary>
		public System.String Tsql
		{
			get	{ return _tsql; }
			set
			{
				if((_tsql != value))
				{
					OnTsqlChanging(value);
					SendPropertyChanging("Tsql");
					_tsql = value;
					SendPropertyChanged("Tsql");
					OnTsqlChanged();
				}
			}
		}

		/// <summary>Gets or sets the XmlEvent field. Mapped on target field 'XmlEvent'. </summary>
		public System.String XmlEvent
		{
			get	{ return _xmlEvent; }
			set
			{
				if((_xmlEvent != value))
				{
					OnXmlEventChanging(value);
					SendPropertyChanging("XmlEvent");
					_xmlEvent = value;
					SendPropertyChanged("XmlEvent");
					OnXmlEventChanged();
				}
			}
		}

		#endregion
	}
}
#pragma warning restore 0649